const i18n = {
	en: {
		theme: "Theme",
		translate: "Translate",
		createAccount: "Create Account",
		password: "Password",
		surname: "Surname",
		name: "Name",
		login: "Login",
		haveAccount: "I have an acoount <a href='login.html'>Login</a",
		titleMessageError: "Sorry!",
		h2Warning: "Choose a strong password:",
		sixCaracter: "- 6 characters",
		oneCapitalLetter: "- 1 capital letter",
		oneNumber: "- 1 number",
		oneSpecialCaracter: "- 1 special character",
		myFiles: "My Files",
		upload: "Upload",
		newFolder: "New Folder",
		delete: "Delete",
		create: "Create",
		move: "Move",
		download: "Download",
	},
	pt: {
		theme: "Tema",
		translate: "Traduzir",
		createAccount: "Criar Conta",
		password: "Senha",
		surname: "Sobrenome",
		name: "Nome",
		login: "Entrar",
		haveAccount: "Já tenho uma conta <a href='login.html'>Entrar</a",
		titleMessageError: "Desculpe!",
		h2Warning: "Escolha uma senha forte:",
		sixCaracter: "- 6 caracteres",
		oneCapitalLetter: "- 1 letra maiúscula",
		oneNumber: "- 1 número",
		oneSpecialCaracter: "- 1 caracter especial",
		myFiles: "Meus Arquivos",
		upload: "Carregar",
		newFolder: "Nova Pasta",
		delete: "Excluir",
		create: "Criar",
		move: "Mover",
		download: "Baixar",
	}
};

export default i18n;